# Generated by Django 5.1 on 2024-11-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_patient_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
